### ISSUE TITLE
Using Carbon types with Symfony3 and Doctrine

### ISSUE THREAD

**Issue by matyunin** [beberlei/DoctrineExtensions#231]
I have simple Doctrine `MyEntity` with `datetime` field and auto-generated getter:

```php
class MyEntity
{
    /**
     * @var Carbon
     * @ORM\Column(name="created_at", type="datetime")
     * @Gedmo\Timestampable(on="create")
     */
    protected $createdAt;

    /**
     * @return Carbon
     */
    public function getCreatedAt(): Carbon
    {
        return $this->createdAt;
    }
}
```

Before installing `DoctrineExtensions` I got this when I try to retrieve `MyEntity` records:

```
Type error: Return value of StoriesBundle\Entity\Comment::getCreatedAt() must be an instance of Carbon\Carbon, instance of DateTime returned
```

Then I installed `DoctrineExtensions` and enabled it in `./app/autoload.php`:

```php
<?php

use Doctrine\Common\Annotations\AnnotationRegistry;
use Composer\Autoload\ClassLoader;

/** @var ClassLoader $loader */
$loader = require __DIR__.'/../vendor/autoload.php';

AnnotationRegistry::registerLoader([$loader, 'loadClass']);

$classLoader = new \Doctrine\Common\ClassLoader('DoctrineExtensions', __DIR__.'/../vendor/beberlei-doctrine-extensions');
$classLoader->register();

return $loader;
```

Then I rewrited field type in my `MyEntity` definition:

```php
class MyEntity
{
    /**
     * @var Carbon
     * @ORM\Column(name="created_at", type="carbondatetime")
     * @Gedmo\Timestampable(on="create")
     */
    protected $createdAt;

    /**
     * @return Carbon
     */
    public function getCreatedAt(): Carbon
    {
        return $this->createdAt;
    }
}
```

And then I got:

```
InvalidMappingException in Annotation.php line 60:
Field - [createdAt] type is not valid and must be 'date', 'datetime' or 'time' in class - AppBundle\Entity\MyEntity
```

How should I use `DoctrineExtensions` to be able to use its custom date types with postgres?

**Comment by stevelacey** [comment]
I imagine you're neglecting to load the type – DoctrineExtensions doesn't register anything by default afaik – example Symfony configuration can be found in https://github.com/beberlei/DoctrineExtensions/blob/master/config/postgres.yml – I expect there's a `types` key for loading these classes in via too.

**Comment by matyunin** [comment]
Thanks! But in `beberlei/DoctrineExtensions/blob/master/config/postgres.yml` I see only function declarations:

```yaml
doctrine:
    orm:
        dql:
            datetime_functions:
                date_format: DoctrineExtensions\Query\Postgresql\DateFormat
                at_time_zone: DoctrineExtensions\Query\Postgresql\AtTimeZoneFunction
            string_functions:
                str_to_date: DoctrineExtensions\Query\Postgresql\StrToDate
                count_filter: DoctrineExtensions\Query\Postgresql\CountFilterFunction
```

How can I declare types?
