### ISSUE TITLE
Symfony3 does not use IfElse

### ISSUE THREAD

**Issue by jakenoble** [beberlei/DoctrineExtensions#253]
My config

```
# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/../var/data/data.sqlite"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        dql:
            string_functions:
                ifelse: DoctrineExtensions\Query\Mysql\IfElse
```

This seems fine. I have updated Composer and can see the class in `vendor`.

Using this function

```
public function tuneRevenueTotal()
{
    $builder = $this->createQueryBuilder('t');

    $builder
        ->join('t.distributions', 'd')
        ->addSelect('IF (LOWER(d.usage_summary) = "online", 1, 0) AS isOnline')
        ->andWhere('d.cae_number = 639769584');

    return $builder->getQuery()->getResult();

}
```

Results in this error "[Syntax Error] line 0, col 10: Error: Expected known function, got 'IF'".

The full query is 

```
SELECT t, IF (LOWER(d.usage_summary) = "online", 1, 0) AS isOnline FROM AppBundle\Entity\Tune t INNER JOIN t.distributions d WHERE d.cae_number = 639769584
```

Which works directly in MySQL.

Have I done something wrong is there an issue with Symfony3 and this library?

**Comment by stevelacey** [comment]
I doubt it is a Symfony3 issue, but I don't see any issues with what you're doing – maybe try see if it work without the `LOWER`? You're going to have to debug this – the error looks like the function is not being loaded.

**Comment by jakenoble** [comment]
Any ideas why it would not be loaded, if I place a `die` inside the class in Vendor I can confirm its not dying and therefore is not being used at all.

**Comment by stevelacey** [comment]
@jakenoble no idea, but I imagine it's an issue with your config yaml – did you have any luck?

**Comment by jakenoble** [comment]
No luck, moved to another solution

**Comment by Blackskyliner** [comment]
If you register it as `ifelse` you will have to use `IFELSE` instead of `IF` within the query, afaik.

**Comment by lucasgranberg** [comment]
Just to confirm, @Blackskyliner is right. If you want to use `IF()` in your queries you can register the extension like this:
```yaml
doctrine:
    ...
    orm:
        ...
        dql:
            ...
            string_functions:
                if: DoctrineExtensions\Query\Mysql\IfElse
```
note the `if:` instead of `ifelse:`
