### ISSUE TITLE
Use in Symfony 3

### ISSUE THREAD

**Issue by Web-Control** [beberlei/DoctrineExtensions#276]
How to register this bundle in Symfony 3?
What should i write in AppKernel.php?  new...

**Comment by mcorteel** [comment]
You don't have to register it in the kernel, but you have to tell doctrine which functions you want to use. For example, I have:
```yml
doctrine:
    orm:
        dql:
            numeric_functions:
                round: DoctrineExtensions\Query\Mysql\Round
            string_functions:
                field: DoctrineExtensions\Query\Mysql\Field
                collate: DoctrineExtensions\Query\Mysql\Collate
                match: DoctrineExtensions\Query\Mysql\MatchAgainst
                soundex: DoctrineExtensions\Query\Mysql\Soundex
            datetime_functions:
                date: DoctrineExtensions\Query\Mysql\Date
                datediff: DoctrineExtensions\Query\Mysql\DateDiff
                datesub: DoctrineExtensions\Query\Mysql\DateSub
                year: DoctrineExtensions\Query\Mysql\Year
                month: DoctrineExtensions\Query\Mysql\Month
                day: DoctrineExtensions\Query\Mysql\Day
                now: DoctrineExtensions\Query\Mysql\Now
                time: DoctrineExtensions\Query\Mysql\Time
                timediff: DoctrineExtensions\Query\Mysql\TimeDiff
```

**Comment by Web-Control** [comment]
I did it. 
I have this: 
`doctrine:
    orm:
        dql:
            string_functions:
                str_to_date: DoctrineExtensions\Query\Mysql\StrToDate`

and it doesnt work :(

**Comment by mcorteel** [comment]
The only thing I can tell you is that you indented the `orm` key (and subsequently all the others) too much.
If `orm` is actually a subkey of another subkey of another `doctrine` subkey (for example `dbal`), it won't work. If you will, the config key in point notation should be `doctrine.orm.dql.string_functions.str_to_date`.

**Comment by pixelfantasy** [comment]
If your are using **multiple entitiy-managers** in your project you have to put the dql-subkey **beneath the named entitymanager** in Symfony 3.x to function properly. Maybe this is the same when only using 1 entity-manager?! Here my renamed but working example of copied from the config.yml:

```
doctrine:
  dbal:
    default_connection: first
    connections:
      first:
        driver:   pdo_mysql
        host:     '%first_database_host%'
        port:     '%first_database_port%'
        dbname:   '%first_database_name%'
        user:     '%first_database_user%'
        password: '%first_database_password%'
        charset:  UTF8
      second:
        driver:   pdo_mysql
        host:     '%second_database_host%'
        port:     '%second_database_port%'
        dbname:   '%second_database_name%'
        user:     '%second_database_user%'
        password: '%second_database_password%'
        charset:  UTF8

  orm:
    default_entity_manager: first
    entity_managers:
      first:
        connection: first
        naming_strategy: doctrine.orm.naming_strategy.underscore
        mappings:
          FirstBundle:
            prefix: FirstBundle\Entity\
      second:
        connection: second
        naming_strategy: doctrine.orm.naming_strategy.underscore
        dql:
          string_functions:
            find_in_set: DoctrineExtensions\Query\Mysql\FindInSet
            collate: DoctrineExtensions\Query\Mysql\Collate
            match: DoctrineExtensions\Query\Mysql\MatchAgainst
        mappings:
          SecondBundle:
            prefix: SecondBundle\Entity\
```
Hope this helps :-)

**Comment by alex8276** [comment]
Hello,
jytjytjrj
I add `beberlei/DoctrineExtensions": "@stable`  in my composer.json and in my config.yml 
```
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        mapping_types:
            enum: string
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.project_dir%/var/data/data.sqlite"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        dql:
            datetime_functions:
                month: DoctrineExtensions\Query\Mysql\Month
                year: DoctrineExtensions\Query\Mysql\Year
```
but I have this error: Attempted to load class "Month" from namespace "DoctrineExtensions\Query\Mysql".
Did you forget a "use" statement for another namespace?
Would you have an idea of the problem ?

Regards
