### ISSUE TITLE
Connect to sf4 project

### ISSUE THREAD

**Issue by bgpastukh** [beberlei/DoctrineExtensions#290]
Hi, i added extensions to my symfony 4 project, but it hasn't work.

My doctrine config:

```
doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: utf8mb4

        # With Symfony 3.3, remove the `resolve:` prefix
        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
        dql:
            string_functions:
                FIELD: DoctrineExtensions\Query\Mysql\Field
                DATE_FORMAT: DoctrineExtensions\Query\Mysql\DateFormat
```
